export const geographyQuestions = {
    easy: [
        { q: '🌏 What is the largest continent?', correct: 'Asia', wrong: ['Africa', 'Europe', 'North America'], flag: '🌏' },
        { q: '🌊 Which ocean is the largest?', correct: 'Pacific', wrong: ['Atlantic', 'Indian', 'Arctic'], flag: '🌊' },
        { q: '🇫🇷 What is the capital of France?', correct: 'Paris', wrong: ['London', 'Berlin', 'Rome'], flag: '🇫🇷' },
        { q: '🇨🇳 Which country has the most people?', correct: 'China', wrong: ['India', 'USA', 'Brazil'], flag: '🇨🇳' },
        { q: '🏞️ What is the longest river?', correct: 'Nile', wrong: ['Amazon', 'Mississippi', 'Yangtze'], flag: '🏞️' },
        { q: '🏜️ Which desert is the largest?', correct: 'Sahara', wrong: ['Gobi', 'Kalahari', 'Atacama'], flag: '🏜️' },
        { q: '🌍 What planet do we live on?', correct: 'Earth', wrong: ['Mars', 'Venus', 'Jupiter'], flag: '🌍' },
        { q: '🗺️ How many continents are there?', correct: '7', wrong: ['5', '6', '8'], flag: '🗺️' },
        { q: '🗻 Which mountain is the highest?', correct: 'Mount Everest', wrong: ['K2', 'Kilimanjaro', 'Denali'], flag: '🗻' },
        { q: '🇺🇸 What is the capital of the USA?', correct: 'Washington, D.C.', wrong: ['New York', 'Los Angeles', 'Chicago'], flag: '🇺🇸' },
        { q: '🌴 Which continent is Egypt part of?', correct: 'Africa', wrong: ['Asia', 'Europe', 'South America'], flag: '🇪🇬' },
        { q: '🏰 What is the capital of the UK?', correct: 'London', wrong: ['Manchester', 'Edinburgh', 'Dublin'], flag: '🇬🇧' },
        { q: '🗽 Where is the Statue of Liberty?', correct: 'New York', wrong: ['Paris', 'London', 'Rome'], flag: '🗽' },
        { q: '🌋 Which island country is near Australia?', correct: 'New Zealand', wrong: ['Fiji', 'Indonesia', 'Philippines'], flag: '🇳🇿' },
        { q: '🏯 What is the capital of China?', correct: 'Beijing', wrong: ['Shanghai', 'Guangzhou', 'Shenzhen'], flag: '🇨🇳' },
        { q: '🦘 Which continent has kangaroos?', correct: 'Australia', wrong: ['Asia', 'Africa', 'Europe'], flag: '🇦🇺' },
        { q: '🦓 Which continent has zebras?', correct: 'Africa', wrong: ['Asia', 'Australia', 'Europe'], flag: '🌍' },
        { q: '🌁 Where is the Golden Gate Bridge?', correct: 'San Francisco', wrong: ['Los Angeles', 'Seattle', 'Chicago'], flag: '🇺🇸' },
        { q: '🛕 What is the capital of India?', correct: 'New Delhi', wrong: ['Mumbai', 'Bangalore', 'Chennai'], flag: '🇮🇳' },
        { q: '🍁 What is the national symbol of Canada?', correct: 'Maple Leaf', wrong: ['Pine Tree', 'Oak Leaf', 'Birch Leaf'], flag: '🇨🇦' },
        { q: '🗼 Where is the Eiffel Tower?', correct: 'Paris', wrong: ['Rome', 'Berlin', 'Madrid'], flag: '🇫🇷' },
        { q: '🌊 What is the ocean near California?', correct: 'Pacific Ocean', wrong: ['Atlantic', 'Indian', 'Arctic'], flag: '🌊' },
        { q: '🏕️ What is the capital of Brazil?', correct: 'Brasília', wrong: ['Rio de Janeiro', 'São Paulo', 'Salvador'], flag: '🇧🇷' },
        { q: '🏝️ Which country is an island?', correct: 'Japan', wrong: ['Germany', 'Mexico', 'France'], flag: '🇯🇵' },
        { q: '🎄 Where is Lapland?', correct: 'Finland', wrong: ['Sweden', 'Russia', 'Iceland'], flag: '🇫🇮' },
        { q: '🦒 What continent has giraffes?', correct: 'Africa', wrong: ['Asia', 'Europe', 'Australia'], flag: '🌍' },
        { q: '🕌 What is the capital of Turkey?', correct: 'Ankara', wrong: ['Istanbul', 'Izmir', 'Bursa'], flag: '🇹🇷' },
        { q: '🏟️ What is the capital of Argentina?', correct: 'Buenos Aires', wrong: ['Lima', 'Santiago', 'Bogotá'], flag: '🇦🇷' },
        { q: '🚢 Which city has the busiest port?', correct: 'Shanghai', wrong: ['Singapore', 'Rotterdam', 'New York'], flag: '🇨🇳' },
        { q: '🍇 Which country is famous for wine?', correct: 'France', wrong: ['Sweden', 'Russia', 'India'], flag: '🇫🇷' },
        { q: '🕌 Which city is known as the Holy City?', correct: 'Jerusalem', wrong: ['Mecca', 'Rome', 'Istanbul'], flag: '🇮🇱' },
        { q: '🌄 Which mountain is in Japan?', correct: 'Mount Fuji', wrong: ['Mount Etna', 'Mount Elbrus', 'Mount Kenya'], flag: '🇯🇵' },
        { q: '⛩️ What is the capital of Thailand?', correct: 'Bangkok', wrong: ['Phuket', 'Chiang Mai', 'Pattaya'], flag: '🇹🇭' },
        { q: '🧊 Which country is known for glaciers?', correct: 'Iceland', wrong: ['Ireland', 'Norway', 'Switzerland'], flag: '🇮🇸' },
        { q: '🐍 What country is famous for the Amazon?', correct: 'Brazil', wrong: ['Peru', 'Colombia', 'Venezuela'], flag: '🇧🇷' },
        { q: '🌈 What is the capital of Ireland?', correct: 'Dublin', wrong: ['Cork', 'Galway', 'Belfast'], flag: '🇮🇪' },
        { q: '🎡 Where is the London Eye?', correct: 'London', wrong: ['Manchester', 'Liverpool', 'Oxford'], flag: '🇬🇧' },
        { q: '🦁 What country is famous for safaris?', correct: 'Kenya', wrong: ['India', 'Australia', 'Mexico'], flag: '🇰🇪' },
        { q: '🎭 What city is famous for carnivals?', correct: 'Rio de Janeiro', wrong: ['Buenos Aires', 'Lisbon', 'Havana'], flag: '🇧🇷' },
        { q: '🦅 What is the capital of Germany?', correct: 'Berlin', wrong: ['Frankfurt', 'Munich', 'Hamburg'], flag: '🇩🇪' },
        { q: '🌪️ Which U.S. state has the most tornadoes?', correct: 'Texas', wrong: ['Florida', 'Oklahoma', 'Kansas'], flag: '🇺🇸' },
        { q: '🗿 Where are the Easter Island statues?', correct: 'Chile', wrong: ['Peru', 'New Zealand', 'Hawaii'], flag: '🇨🇱' },
        { q: '🏖️ What is the capital of Greece?', correct: 'Athens', wrong: ['Thessaloniki', 'Santorini', 'Crete'], flag: '🇬🇷' },
        { q: '🧀 What country is known for cheese?', correct: 'Switzerland', wrong: ['Italy', 'Germany', 'Norway'], flag: '🇨🇭' },
        { q: '🚄 Which country has bullet trains?', correct: 'Japan', wrong: ['France', 'USA', 'South Korea'], flag: '🇯🇵' },
        { q: '🐼 Which country is home to pandas?', correct: 'China', wrong: ['India', 'Thailand', 'Nepal'], flag: '🇨🇳' },
        { q: '🎇 Which city is famous for New Years fireworks?', correct: 'Sydney', wrong: ['New York', 'Tokyo', 'Paris'], flag: '🇦🇺' },
        { q: '🧱 Where is the Great Wall located?', correct: 'China', wrong: ['India', 'Russia', 'Japan'], flag: '🇨🇳' },
        { q: '🕍 What is the capital of Israel?', correct: 'Jerusalem', wrong: ['Tel Aviv', 'Haifa', 'Nazareth'], flag: '🇮🇱' },
    ],
    medium: [
        { q: '🇦🇺 What is the capital of Australia?', correct: 'Canberra', wrong: ['Sydney', 'Melbourne', 'Perth'], flag: '🇦🇺' },
        { q: '🏔️ Which mountain range has Mt. Everest?', correct: 'Himalayas', wrong: ['Andes', 'Alps', 'Rockies'], flag: '🏔️' },
        { q: '🇻🇦 What is the smallest country?', correct: 'Vatican City', wrong: ['Monaco', 'San Marino', 'Liechtenstein'], flag: '🇻🇦' },
        { q: '🏜️ Which desert is the largest?', correct: 'Sahara', wrong: ['Gobi', 'Kalahari', 'Atacama'], flag: '🏜️' },
        { q: '🇨🇦 What is the capital of Canada?', correct: 'Ottawa', wrong: ['Toronto', 'Vancouver', 'Montreal'], flag: '🇨🇦' },
        { q: '🌎 Which continent is Brazil in?', correct: 'South America', wrong: ['Africa', 'Asia', 'North America'], flag: '🇧🇷' },
        { q: '🇯🇵 What is the capital of Japan?', correct: 'Tokyo', wrong: ['Kyoto', 'Osaka', 'Nagoya'], flag: '🇯🇵' },
        { q: '🗿 Which continent has the most countries?', correct: 'Africa', wrong: ['Europe', 'Asia', 'South America'], flag: '🌍' },
        { q: '🌬️ Which country is known as the Land of the Windmills?', correct: 'Netherlands', wrong: ['Germany', 'Denmark', 'Belgium'], flag: '🇳🇱' },
        { q: '🎋 What is the capital of South Korea?', correct: 'Seoul', wrong: ['Busan', 'Incheon', 'Daegu'], flag: '🇰🇷' },
        // 40 more unique medium questions...
        { q: '🗻 Which mountain is in the Himalayas?', correct: 'Everest', wrong: ['Fuji', 'Andes', 'Rockies'], flag: '🏔️' },
        { q: '🇧🇷 What is the largest country in South America?', correct: 'Brazil', wrong: ['Argentina', 'Chile', 'Colombia'], flag: '🇧🇷' },
        { q: '🌎 What continent is Mexico in?', correct: 'North America', wrong: ['South America', 'Europe', 'Asia'], flag: '🇲🇽' },
        { q: '🇪🇸 What is the capital of Spain?', correct: 'Madrid', wrong: ['Barcelona', 'Valencia', 'Seville'], flag: '🇪🇸' },
        { q: '🧭 What line divides the Earth into North and South?', correct: 'Equator', wrong: ['Prime Meridian', 'Tropic of Cancer', 'Greenwich'], flag: '🌐' },
        { q: '🌆 What is the capital of Argentina?', correct: 'Buenos Aires', wrong: ['Lima', 'Bogotá', 'Santiago'], flag: '🇦🇷' },
        { q: '🌋 Which volcano destroyed Pompeii?', correct: 'Mount Vesuvius', wrong: ['Mount Etna', 'Krakatoa', 'Mount Fuji'], flag: '🌋' },
        { q: '🇰🇪 What is the capital of Kenya?', correct: 'Nairobi', wrong: ['Mombasa', 'Kampala', 'Addis Ababa'], flag: '🇰🇪' },
        { q: '🌐 What is the Prime Meridian used for?', correct: 'Time zones', wrong: ['Weather', 'Travel', 'Earthquakes'], flag: '🕰️' },
        { q: '🇿🇦 What is the capital of South Africa?', correct: 'Pretoria', wrong: ['Cape Town', 'Johannesburg', 'Durban'], flag: '🇿🇦' }
    ],
    hard: [
        { q: '🇰🇿 What is the capital of Kazakhstan?', correct: 'Nur-Sultan', wrong: ['Almaty', 'Shymkent', 'Aktobe'], flag: '🇰🇿' },
        { q: '🌉 Which strait separates Europe and Asia?', correct: 'Bosphorus', wrong: ['Gibraltar', 'Hormuz', 'Malacca'], flag: '🌉' },
        { q: '🌊 What is the deepest ocean trench?', correct: 'Mariana Trench', wrong: ['Puerto Rico Trench', 'Java Trench', 'Peru-Chile Trench'], flag: '🌊' },
        { q: '🇷🇺 Which country has the most time zones?', correct: 'Russia', wrong: ['USA', 'China', 'Australia'], flag: '🇷🇺' },
        { q: '🇧🇹 What is the capital of Bhutan?', correct: 'Thimphu', wrong: ['Paro', 'Punakha', 'Jakar'], flag: '🇧🇹' },
        { q: '🌏 What island is the largest in the world?', correct: 'Greenland', wrong: ['Australia', 'Borneo', 'New Guinea'], flag: '🇬🇱' },
        { q: '🌋 What is the most active volcano?', correct: 'Kilauea', wrong: ['Etna', 'Vesuvius', 'Fuji'], flag: '🌋' },
        { q: '🏰 What is the capital of Liechtenstein?', correct: 'Vaduz', wrong: ['Bern', 'Luxembourg', 'Innsbruck'], flag: '🇱🇮' },
        { q: '🗺️ Which country borders the most other countries?', correct: 'Russia', wrong: ['China', 'Brazil', 'Germany'], flag: '🗺️' },
        { q: '🏝️ What is the capital of the Maldives?', correct: 'Malé', wrong: ['Colombo', 'Seychelles', 'Suva'], flag: '🇲🇻' },
        // 40 more unique hard questions...
        { q: '🗺️ What is the antipode of New Zealand?', correct: 'Spain', wrong: ['Brazil', 'USA', 'China'], flag: '🌏' },
        { q: '🇲🇩 What is the capital of Moldova?', correct: 'Chișinău', wrong: ['Tirana', 'Riga', 'Skopje'], flag: '🇲🇩' },
        { q: '🌍 What country lies between Norway and Finland?', correct: 'Sweden', wrong: ['Denmark', 'Poland', 'Germany'], flag: '🇸🇪' },
        { q: '🌌 Which country is closest to the North Pole?', correct: 'Norway', wrong: ['Canada', 'Russia', 'Greenland'], flag: '🇳🇴' },
        { q: '🛣️ What is the longest road in the world?', correct: 'Pan-American Highway', wrong: ['Trans-Siberian Highway', 'Route 66', 'Highway 1'], flag: '🌎' },
        { q: '🏜️ What desert is in Mongolia?', correct: 'Gobi', wrong: ['Sahara', 'Kalahari', 'Thar'], flag: '🏜️' },
        { q: '🏝️ What is the capital of the Maldives?', correct: 'Malé', wrong: ['Colombo', 'Dhaka', 'Jakarta'], flag: '🇲🇻' },
        { q: '🌊 What sea lies between Europe and Africa?', correct: 'Mediterranean', wrong: ['Caribbean', 'Black Sea', 'Baltic Sea'], flag: '🌊' },
        { q: '🏔️ Which mountain range is in South America?', correct: 'Andes', wrong: ['Himalayas', 'Rockies', 'Alps'], flag: '🇵🇪' },
        { q: '🇹🇷 What is the capital of Turkey?', correct: 'Ankara', wrong: ['Istanbul', 'Izmir', 'Antalya'], flag: '🇹🇷' },
    ]
};
