export const scienceQuestions = {
  easy: [
    { q: '🌱 What do plants need to make food?', correct: 'Sunlight', wrong: ['Water only', 'Soil only', 'Air only'] },
    { q: '🕷️ How many legs does a spider have?', correct: '8', wrong: ['6', '10', '4'] },
    { q: '💨 What do we breathe in?', correct: 'Oxygen', wrong: ['Carbon', 'Nitrogen', 'Helium'] },
    { q: '🌞 What is the closest star to Earth?', correct: 'Sun', wrong: ['Moon', 'Mars', 'Venus'] },
    { q: '🐝 What do bees make?', correct: 'Honey', wrong: ['Milk', 'Butter', 'Cheese'] },
    { q: '🦴 What are our bones made of?', correct: 'Calcium', wrong: ['Iron', 'Zinc', 'Magnesium'] },
    { q: '🧠 What organ helps us think?', correct: 'Brain', wrong: ['Heart', 'Liver', 'Lungs'] },
    { q: '🚰 Where does clean drinking water come from?', correct: 'Tap', wrong: ['Sea', 'Rain', 'River'] },
    { q: '🌧️ What falls from clouds as rain?', correct: 'Water', wrong: ['Dust', 'Air', 'Steam'] },
    { q: '🔥 What is needed to start a fire?', correct: 'Heat', wrong: ['Water', 'Sand', 'Ice'] },
    { q: '🐾 What do cats usually land on?', correct: 'Feet', wrong: ['Back', 'Tail', 'Head'] },
    { q: '🍎 Which part of the plant do we eat in an apple?', correct: 'Fruit', wrong: ['Leaf', 'Stem', 'Root'] },
    { q: '🐬 Which animal lives in the ocean?', correct: 'Dolphin', wrong: ['Tiger', 'Monkey', 'Cow'] },
    { q: '☁️ What are clouds made of?', correct: 'Water droplets', wrong: ['Dust', 'Gas', 'Light'] },
    { q: '🦷 What do we use to chew food?', correct: 'Teeth', wrong: ['Tongue', 'Lips', 'Jaw'] },
    { q: '👃 What organ do we use to smell?', correct: 'Nose', wrong: ['Ear', 'Eye', 'Mouth'] },
    { q: '🎈 Why do balloons float?', correct: 'Helium', wrong: ['Air', 'Oxygen', 'Smoke'] },
    { q: '🚦 What color means stop?', correct: 'Red', wrong: ['Green', 'Yellow', 'Blue'] },
    { q: '🧃 What liquid do cows give?', correct: 'Milk', wrong: ['Juice', 'Oil', 'Syrup'] },
    { q: '🧊 What is frozen water called?', correct: 'Ice', wrong: ['Steam', 'Rain', 'Cloud'] },
    // ... add 30 more easy questions
     { q: '🍞 Bread is made from what?', correct: 'Wheat', wrong: ['Corn', 'Sugar', 'Milk'] },
    { q: '🐾 Which animal barks?', correct: 'Dog', wrong: ['Cat', 'Cow', 'Horse'] },
    { q: '🦆 Ducks can...', correct: 'Swim and fly', wrong: ['Only swim', 'Only walk', 'Only fly'] },
    { q: '🐘 Which is the largest land animal?', correct: 'Elephant', wrong: ['Lion', 'Giraffe', 'Tiger'] },
    { q: '🕊️ What bird is a symbol of peace?', correct: 'Dove', wrong: ['Crow', 'Sparrow', 'Owl'] },
    { q: '🔋 What gives power to a toy car?', correct: 'Battery', wrong: ['Water', 'Air', 'Paper'] },
    { q: '🎈 What makes balloons float?', correct: 'Helium', wrong: ['Oxygen', 'Hydrogen', 'Nitrogen'] },
    { q: '🚽 Where does waste go?', correct: 'Toilet', wrong: ['Sink', 'Fridge', 'Shelf'] },
    { q: '🧃 Which drink is healthy?', correct: 'Fruit juice', wrong: ['Soda', 'Cola', 'Coffee'] },
    { q: '🛁 Where do we take a bath?', correct: 'Bathroom', wrong: ['Kitchen', 'Balcony', 'Garden'] },
    { q: '🎨 What do we use to paint?', correct: 'Brush', wrong: ['Spoon', 'Knife', 'Stick'] },
    { q: '🐔 Which bird lays eggs we eat?', correct: 'Hen', wrong: ['Crow', 'Eagle', 'Duck'] },
    { q: '📱 What do we call a smart device?', correct: 'Phone', wrong: ['Book', 'Table', 'TV'] },
    { q: '🧊 Ice is...', correct: 'Frozen water', wrong: ['Frozen oil', 'Frozen juice', 'Rock'] },
    { q: '🦴 What protects our brain?', correct: 'Skull', wrong: ['Skin', 'Lungs', 'Back'] },
    { q: '🚦 What color means GO?', correct: 'Green', wrong: ['Red', 'Yellow', 'Blue'] },
    { q: '🌍 Earth is a...', correct: 'Planet', wrong: ['Star', 'Comet', 'Moon'] },
    { q: '🐠 Which animal lives in water?', correct: 'Fish', wrong: ['Monkey', 'Elephant', 'Lion'] },
    { q: '🌪️ What is a fast spinning wind called?', correct: 'Tornado', wrong: ['Storm', 'Cloud', 'Drizzle'] },
    { q: '🌈 What comes after rain sometimes?', correct: 'Rainbow', wrong: ['Snow', 'Fog', 'Thunder'] },

    { q: '🐛 What does a caterpillar turn into?', correct: 'Butterfly', wrong: ['Bee', 'Bug', 'Dragonfly'] },
    { q: '🦷 What do we brush?', correct: 'Teeth', wrong: ['Hair', 'Ears', 'Hands'] },
    { q: '📚 Where do we learn science?', correct: 'School', wrong: ['Park', 'Kitchen', 'Garage'] },
    { q: '🌜 What shines at night?', correct: 'Moon', wrong: ['Sun', 'Tree', 'Ocean'] },
    { q: '🚗 What moves on wheels?', correct: 'Car', wrong: ['Book', 'Rock', 'Tree'] },
    { q: '📦 What keeps things safe?', correct: 'Box', wrong: ['Bag', 'Chair', 'Plate'] },
    { q: '🐻 What animal hibernates in winter?', correct: 'Bear', wrong: ['Dog', 'Deer', 'Tiger'] },
    { q: '🌽 Corn is a...', correct: 'Vegetable', wrong: ['Fruit', 'Drink', 'Toy'] },
    { q: '🧃 What is made by squeezing oranges?', correct: 'Juice', wrong: ['Soup', 'Milk', 'Tea'] },
    { q: '🔦 What helps us see in the dark?', correct: 'Torch', wrong: ['Mirror', 'Book', 'Fan'] },
    { q: '🚴 What has two wheels and pedals?', correct: 'Bicycle', wrong: ['Car', 'Train', 'Skateboard'] },

    { q: '📏 What tool measures length?', correct: 'Ruler', wrong: ['Clock', 'Scale', 'Brush'] },
    { q: '⚡ What gives us electricity at home?', correct: 'Wires', wrong: ['Pipes', 'Ropes', 'Tubes'] },
    { q: '🛫 What flies in the sky with passengers?', correct: 'Airplane', wrong: ['Bird', 'Balloon', 'Helicopter'] },
    { q: '🖼️ What do we hang on a wall to view?', correct: 'Picture', wrong: ['Carpet', 'Table', 'Pillow'] },
    { q: '🐢 Which animal is very slow?', correct: 'Turtle', wrong: ['Dog', 'Rabbit', 'Cat'] },
    { q: '🦁 King of the jungle?', correct: 'Lion', wrong: ['Tiger', 'Bear', 'Wolf'] },
    { q: '🎵 What helps us hear music?', correct: 'Ear', wrong: ['Eye', 'Nose', 'Hand'] },
    { q: '🧽 What do we use to clean dishes?', correct: 'Sponge', wrong: ['Brush', 'Fork', 'Mug'] },
    { q: '🎓 Who teaches in school?', correct: 'Teacher', wrong: ['Chef', 'Doctor', 'Pilot'] },
    { q: '📦 What do we use to carry things?', correct: 'Bag', wrong: ['Plate', 'Book', 'Brush'] }

  ],
  medium: [
   { q: '🪐 What is the largest planet?', correct: 'Jupiter', wrong: ['Saturn', 'Earth', 'Mars'] },
    { q: '🌿 What gas do plants release?', correct: 'Oxygen', wrong: ['Carbon dioxide', 'Nitrogen', 'Hydrogen'] },
    { q: '🦴 How many bones are in a human body?', correct: '206', wrong: ['156', '306', '256'] },
    { q: '💎 What is the hardest natural substance?', correct: 'Diamond', wrong: ['Gold', 'Iron', 'Silver'] },
    { q: '❤️ What organ pumps blood?', correct: 'Heart', wrong: ['Liver', 'Kidney', 'Lungs'] },
    { q: '🧪 Which state of matter is water vapor?', correct: 'Gas', wrong: ['Liquid', 'Solid', 'Plasma'] },
    { q: '🧲 What is attracted to magnets?', correct: 'Iron', wrong: ['Plastic', 'Glass', 'Wood'] },
    { q: '🌊 What covers most of Earth’s surface?', correct: 'Water', wrong: ['Land', 'Sand', 'Ice'] },
    { q: '🧬 What carries genetic information?', correct: 'DNA', wrong: ['RNA', 'Blood', 'Skin'] },
    { q: '🕰️ What tool measures time?', correct: 'Clock', wrong: ['Ruler', 'Thermometer', 'Microscope'] },
    { q: '🌡️ What tool checks body temperature?', correct: 'Thermometer', wrong: ['Scale', 'Meter', 'Barometer'] },
    { q: '🔋 What stores energy?', correct: 'Battery', wrong: ['Wire', 'Lightbulb', 'Switch'] },
    { q: '💡 What do we use to see in the dark?', correct: 'Light', wrong: ['Wind', 'Fire', 'Mirror'] },
    { q: '📡 What sends signals to your phone?', correct: 'Satellite', wrong: ['Clouds', 'Radio', 'Stars'] },
    { q: '💧 What form of water is rain?', correct: 'Liquid', wrong: ['Solid', 'Gas', 'Steam'] },
    { q: '🐠 What do fish use to breathe?', correct: 'Gills', wrong: ['Lungs', 'Mouth', 'Fins'] },
    { q: '🌪️ What kind of storm spins in a circle?', correct: 'Tornado', wrong: ['Hurricane', 'Thunderstorm', 'Snowstorm'] },
    { q: '📏 What tool measures length?', correct: 'Ruler', wrong: ['Clock', 'Thermometer', 'Scale'] },
    { q: '🔍 What tool helps us see tiny things?', correct: 'Microscope', wrong: ['Telescope', 'Binoculars', 'Magnifying glass'] },
    { q: '🧼 What do we use to stay clean?', correct: 'Soap', wrong: ['Salt', 'Sugar', 'Sand'] },
    // ... add 30 more medium questions
    { q: '🪐 Which planet is the biggest in our solar system?', correct: 'Jupiter', wrong: ['Mars', 'Earth', 'Venus'] },
    { q: '🌳 What gas do trees produce?', correct: 'Oxygen', wrong: ['Hydrogen', 'Carbon', 'Nitrogen'] },
    { q: '🦴 How many bones are in the adult human body?', correct: '206', wrong: ['106', '306', '250'] },
    { q: '💎 What is the hardest natural substance?', correct: 'Diamond', wrong: ['Gold', 'Iron', 'Granite'] },
    { q: '❤️ Which organ pumps blood through the body?', correct: 'Heart', wrong: ['Lungs', 'Liver', 'Brain'] },
    { q: '⚡ What type of energy powers lightning?', correct: 'Electricity', wrong: ['Heat', 'Sound', 'Wind'] },
    { q: '🌪️ What is a tornado made of?', correct: 'Air', wrong: ['Water', 'Dust', 'Fire'] },
    { q: '🔭 What tool is used to see stars?', correct: 'Telescope', wrong: ['Microscope', 'Periscope', 'Camera'] },
    { q: '🌡️ What measures temperature?', correct: 'Thermometer', wrong: ['Barometer', 'Speedometer', 'Altimeter'] },
    { q: '🧪 What is H2O?', correct: 'Water', wrong: ['Hydrogen', 'Salt', 'Oxygen'] },
    { q: '🪺 What do birds use to build nests?', correct: 'Twigs', wrong: ['Rocks', 'Sand', 'Leaves'] },
    { q: '🐝 What part of a flower attracts bees?', correct: 'Petal', wrong: ['Root', 'Stem', 'Leaf'] },
    { q: '🌍 Which planet do we live on?', correct: 'Earth', wrong: ['Mars', 'Venus', 'Jupiter'] },
    { q: '🌊 What covers most of the Earth surface?', correct: 'Water', wrong: ['Land', 'Ice', 'Mountains'] },
    { q: '🧲 What attracts iron?', correct: 'Magnet', wrong: ['Copper', 'Plastic', 'Wood'] },
    { q: '🌫️ What causes fog?', correct: 'Water droplets', wrong: ['Smoke', 'Clouds', 'Dust'] },
    { q: '🧠 What does your brain help you do?', correct: 'Think', wrong: ['Jump', 'Eat', 'Sleep'] },
    { q: '🔊 What do we use to hear sound?', correct: 'Ears', wrong: ['Eyes', 'Nose', 'Mouth'] },
    { q: '🧃 What keeps you hydrated?', correct: 'Water', wrong: ['Soda', 'Juice', 'Tea'] },
    { q: '👃 What helps you smell things?', correct: 'Nose', wrong: ['Ear', 'Eye', 'Tongue'] },
    { q: '🪞 What reflects your image?', correct: 'Mirror', wrong: ['Window', 'Door', 'TV'] },
    { q: '🌧️ What comes from clouds?', correct: 'Rain', wrong: ['Dust', 'Light', 'Stars'] },
    { q: '🦷 What do we use to chew food?', correct: 'Teeth', wrong: ['Nose', 'Lips', 'Ears'] },
    { q: '🐟 Where do fish live?', correct: 'Water', wrong: ['Air', 'Land', 'Trees'] },
    { q: '🐶 What animal is known as mans best friend?', correct: 'Dog', wrong: ['Cat', 'Horse', 'Bird'] },
    { q: '🍽️ What do humans need to eat?', correct: 'Food', wrong: ['Water', 'Air', 'Light'] },
    { q: '🌈 What natural phenomenon has many colors?', correct: 'Rainbow', wrong: ['Sunlight', 'Fog', 'Wind'] },
    { q: '🌦️ What tool helps predict the weather?', correct: 'Barometer', wrong: ['Speedometer', 'Thermometer', 'Altimeter'] },
    { q: '🦠 What causes colds?', correct: 'Virus', wrong: ['Fungus', 'Bacteria', 'Worms'] },
    { q: '🍀 Which plant is a symbol of luck?', correct: 'Four-leaf clover', wrong: ['Rose', 'Daisy', 'Sunflower'] },
    { q: '🪨 What is solid rock called?', correct: 'Stone', wrong: ['Clay', 'Mud', 'Sand'] },
    { q: '🎈 What gas is in balloons that float?', correct: 'Helium', wrong: ['Oxygen', 'Nitrogen', 'Hydrogen'] },
    { q: '🦕 What are ancient reptiles called?', correct: 'Dinosaurs', wrong: ['Mammals', 'Birds', 'Amphibians'] },
    { q: '🐛 What do caterpillars turn into?', correct: 'Butterflies', wrong: ['Beetles', 'Spiders', 'Flies'] },
    { q: '👁️ What helps you see?', correct: 'Eyes', wrong: ['Ears', 'Hands', 'Feet'] },
    { q: '🧊 What is frozen water called?', correct: 'Ice', wrong: ['Steam', 'Gas', 'Snow'] },
    { q: '🌬️ What makes leaves blow?', correct: 'Wind', wrong: ['Rain', 'Light', 'Heat'] },
    { q: '🌋 What erupts with lava?', correct: 'Volcano', wrong: ['Mountain', 'Cave', 'Hill'] },
    { q: '🌙 What comes out at night?', correct: 'Moon', wrong: ['Sun', 'Rain', 'Clouds'] },
    { q: '⚖️ What tool measures weight?', correct: 'Scale', wrong: ['Ruler', 'Timer', 'Beaker'] }
    
  ],
  hard: [
   { q: '⚡ What is the speed of light?', correct: '299,792,458 m/s', wrong: ['300,000 m/s', '250,000 m/s', '350,000 m/s'] },
    { q: '🥇 What is the symbol for gold?', correct: 'Au', wrong: ['Go', 'Gd', 'Ag'] },
    { q: '🫀 How many chambers does a human heart have?', correct: '4', wrong: ['2', '3', '6'] },
    { q: '🔬 What is the smallest unit of matter?', correct: 'Atom', wrong: ['Molecule', 'Cell', 'Particle'] },
    { q: '🌎 What causes seasons on Earth?', correct: "Earth's tilt", wrong: ['Distance from Sun', 'Moon phases', 'Solar flares'] },
    { q: '🌌 What galaxy do we live in?', correct: 'Milky Way', wrong: ['Andromeda', 'Orion', 'Solar'] },
    { q: '🧫 What is studied in microbiology?', correct: 'Microorganisms', wrong: ['Bones', 'Stars', 'Plants'] },
    { q: '🌡️ What does a thermometer measure?', correct: 'Temperature', wrong: ['Time', 'Speed', 'Weight'] },
    { q: '⚛️ What is the center of an atom called?', correct: 'Nucleus', wrong: ['Core', 'Shell', 'Electron'] },
    { q: '🚀 What force pulls things toward Earth?', correct: 'Gravity', wrong: ['Magnetism', 'Inertia', 'Friction'] },
    { q: '🔋 What is the unit of electric current?', correct: 'Ampere', wrong: ['Volt', 'Watt', 'Ohm'] },
    { q: '🌡️ What is absolute zero?', correct: '-273.15°C', wrong: ['0°C', '-100°C', '-500°C'] },
    { q: '🧪 What does pH measure?', correct: 'Acidity', wrong: ['Density', 'Volume', 'Speed'] },
    { q: '🧬 What shape is DNA?', correct: 'Double helix', wrong: ['Square', 'Circle', 'Straight line'] },
    { q: '🔭 Who proposed the heliocentric model?', correct: 'Copernicus', wrong: ['Newton', 'Einstein', 'Galileo'] },
    { q: '🧠 What lobe of the brain controls thinking?', correct: 'Frontal lobe', wrong: ['Parietal', 'Temporal', 'Occipital'] },
    { q: '☢️ What does radioactive decay emit?', correct: 'Radiation', wrong: ['Heat', 'Light', 'Water'] },
    { q: '💡 Who invented the light bulb?', correct: 'Thomas Edison', wrong: ['Einstein', 'Tesla', 'Newton'] },
    { q: '🧲 What field surrounds a magnet?', correct: 'Magnetic field', wrong: ['Electric field', 'Solar field', 'Nuclear field'] },
    { q: '🔋 What stores electrical charge?', correct: 'Capacitor', wrong: ['Battery', 'Diode', 'Resistor'] },
    // ... add 30 more hard questions
  ]
};

