export const planets = [
  {
    name: 'Mercury',
    emoji: '☿️',
    fact: 'Closest to the Sun – super hot!',
    color: 'bg-gray-400',
    type: 'Terrestrial',
    distance: '58 million km',
    moons: 0,
    atmosphere: 'Almost none (trace oxygen, sodium)',
    temperatureRange: '-180°C to 430°C',
    rotationPeriod: '59 Earth days',
    orbitalPeriod: '88 Earth days',
    surface: 'Craters, ridges, and rocky plains',
    details: 'Mercury is a small, rocky planet with no air and extreme temperatures. It has a surface full of craters from meteor impacts and long cliffs that formed when the planet cooled and shrank.',
    funFact: '☄️ Mercury has ice at its poles—even though it’s so close to the Sun! Its sky is always black because there’s no atmosphere to scatter light.',
    discovery: 'Known since ancient times'
  },
  {
    name: 'Venus',
    emoji: '🌋',
    fact: 'The hottest planet of all',
    color: 'bg-yellow-400',
    type: 'Terrestrial',
    distance: '108 million km',
    moons: 0,
    atmosphere: 'Carbon dioxide, thick sulfuric clouds',
    temperatureRange: 'Around 470°C constantly!',
    rotationPeriod: '243 Earth days (retrograde)',
    orbitalPeriod: '225 Earth days',
    surface: 'Volcanoes, mountains, dry valleys',
    details: 'Venus is wrapped in thick yellow clouds that trap heat like a giant greenhouse. It has hundreds of volcanoes and mountains, and no water. Its surface is dry and rocky, and winds blow faster than hurricanes!',
    funFact: '🌪️ A day on Venus is longer than its year, and the Sun rises in the west and sets in the east—opposite from Earth!',
    discovery: 'Visible to ancient civilizations as morning/evening star'
  },
  {
    name: 'Earth',
    emoji: '🌍',
    fact: 'The only planet with life!',
    color: 'bg-blue-400',
    type: 'Terrestrial',
    distance: '150 million km',
    moons: 1,
    atmosphere: 'Nitrogen, oxygen, traces of other gases',
    temperatureRange: '-89°C to 58°C',
    rotationPeriod: '24 hours',
    orbitalPeriod: '365.25 days',
    surface: 'Oceans, continents, forests, deserts, ice caps',
    details: 'Earth is our amazing home filled with air, water, plants, animals, and people. It has oceans that cover most of its surface, land that changes with tectonic plates, and a protective atmosphere that keeps us warm.',
    funFact: '🌈 Earth’s gravity keeps the Moon in orbit and creates tides. It’s the only planet known to have intelligent life and chocolate!',
    discovery: 'Home planet — no discovery needed 😉'
  },
  {
    name: 'Mars',
    emoji: '🪐',
    fact: 'The dusty red planet',
    color: 'bg-red-400',
    type: 'Terrestrial',
    distance: '228 million km',
    moons: 2,
    atmosphere: 'Thin carbon dioxide',
    temperatureRange: '-140°C to 30°C',
    rotationPeriod: '24.6 hours',
    orbitalPeriod: '687 Earth days',
    surface: 'Dusty deserts, volcanoes, dry riverbeds',
    details: 'Mars is red because of iron oxide dust. It has the largest volcano (Olympus Mons) and canyon (Valles Marineris) in the solar system. Mars has seasons, dust storms, and signs that water once flowed on its surface.',
    funFact: '🔭 Scientists are exploring Mars for signs of past life, and one day humans may live there! NASA’s Perseverance rover is searching for clues right now.',
    discovery: 'Observed since 2nd millennium BCE'
  },
  {
    name: 'Jupiter',
    emoji: '☁️',
    fact: 'Biggest planet with giant storms!',
    color: 'bg-orange-400',
    type: 'Gas Giant',
    distance: '778 million km',
    moons: 95,
    atmosphere: 'Hydrogen, helium, ammonia',
    temperatureRange: '-145°C (cloud tops)',
    rotationPeriod: '10 hours (fastest)',
    orbitalPeriod: '12 Earth years',
    surface: 'No solid surface – swirling gas clouds',
    details: 'Jupiter is the largest planet and spins so fast it bulges at the equator. It’s surrounded by thick clouds and violent storms, including the Great Red Spot, a storm larger than Earth that has lasted over 300 years!',
    funFact: '🌪️ Jupiter’s magnetic field is 14x stronger than Earth’s. It protects many moons—including Europa, which might have an ocean under its ice!',
    discovery: 'Discovered by Galileo in 1610 with a telescope'
  },
  {
    name: 'Saturn',
    emoji: '💍',
    fact: 'Has stunning icy rings',
    color: 'bg-yellow-300',
    type: 'Gas Giant',
    distance: '1.4 billion km',
    moons: 146,
    atmosphere: 'Hydrogen, helium, methane',
    temperatureRange: '-178°C',
    rotationPeriod: '10.7 hours',
    orbitalPeriod: '29 Earth years',
    surface: 'No solid surface – gas and liquid',
    details: 'Saturn’s wide rings are made of millions of ice and rock chunks. Though it looks light and airy, Saturn is powerful, with many moons including Titan, which has rivers and lakes made of methane.',
    funFact: '🧊 If you could find a big enough tub, Saturn would float in it! Its rings stretch 282,000 km wide—almost the distance from Earth to the Moon.',
    discovery: 'Known since ancient Babylonian times'
  },
  {
    name: 'Uranus',
    emoji: '🌀',
    fact: 'Spins on its side!',
    color: 'bg-cyan-300',
    type: 'Ice Giant',
    distance: '2.9 billion km',
    moons: 27,
    atmosphere: 'Hydrogen, helium, methane',
    temperatureRange: '-224°C',
    rotationPeriod: '17 hours',
    orbitalPeriod: '84 Earth years',
    surface: 'Icy atmosphere with gas core',
    details: 'Uranus is pale blue due to methane and rotates on its side, like a rolling ball. It has rings, storms, and a chilly atmosphere that makes it one of the coldest planets in our solar system.',
    funFact: '❄️ Uranus was the first planet discovered with a telescope. It’s tilted 98°, so its seasons last over 20 years each!',
    discovery: 'Discovered by William Herschel in 1781'
  },
  {
    name: 'Neptune',
    emoji: '🌊',
    fact: 'Farthest and windiest planet',
    color: 'bg-blue-300',
    type: 'Ice Giant',
    distance: '4.5 billion km',
    moons: 14,
    atmosphere: 'Hydrogen, helium, methane',
    temperatureRange: '-214°C',
    rotationPeriod: '16 hours',
    orbitalPeriod: '165 Earth years',
    surface: 'Gas surface with deep storm layers',
    details: 'Neptune is a cold, blue world known for its wild weather. Winds blow faster than sound, and it has a giant dark storm like Jupiter’s red spot. Its moon Triton orbits backward!',
    funFact: '🌀 Neptune’s winds are the fastest in the solar system—over 2,000 km/h! It was discovered using math before being seen with a telescope.',
    discovery: 'Discovered in 1846 after predicting its orbit'
  }
];
